### ISSUE TITLE
As a Doctor I need a custom patient proforma for blood cultures

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid-rfh#1]
So that I can enter the details we wish to be able to analyse later.

- [ ] I can find or create a patient (v. similar to current referral logic/screens)
- [ ] I have a multi-step form that gives me:
  - [ ] Diagnosis 
  - [ ] Lines 
  - [ ] Antimicrobials
  - [ ] Blood Cultures

**Comment by fredkingham** [comment]
btw, this is essentially done, but in practice not done. Its done in that it will save to the db with the required fields creating a new episode if necessary and save lines/antimicrobials/blood cultures.

However I think maybe what we actually want is that when we query for an episode we should return the episode and all its info, then update the rest of the fields accordingly with 1 -> many forms for non singletons. Or am I over complicating things?

Either way, its a working prototype (currently not pushed to the test server) on initial-blood-cultures
