### ISSUE TITLE
Please I beg you to protect your secrets.

### ISSUE THREAD

**Issue by tigthor** [openhealthcare/elcid-rfh#1011]
**Hello My Friend that I've not met.**
As we all know the internet is becoming a large place or a large field and and we should start caring for security. And as long s I know the consequences companies or people met when they are breached. That is why i recommend you to either hide or remove this [Exposed PostgreSQL file which contains db passwords](https://github.com/openhealthcare/elcid-rfh/blob/b81e9dd46ac56a4de7f16d57dc0872a3a78bcce9/etc/conf_templates/pgpass.conf.jinja2) . You may see it as a small problem but trust me my friend ,a malicious person getting your private things like passwords. The effect can be devastating. 
Thank You my Friend.

**Comment by davidmiller** [comment]
Unfortunately you are mistaken. That is not an "Exposed PostgreSQL" file, it does not contain database passwords.

You may see it as a small problem to open spam issues on repositories you do not understand, but trust me my friend, it is a waste of other people's time. The effect can be irritating.
