### ISSUE TITLE
Flag whether a patient has had a blood culture in the last 6 months

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid-rfh#122]
Short term this should be 'has been on Bacteraemia list' in the last 6 months
Med. term with results let's query results

Should appear on the list overview and the detail screen

**Comment by emmanuelwey** [comment]
Historical Blood culture flag in red works. Can i ask whether we can toggle this between active bollod culture and historical or whether that will be a separate tag?

**Comment by fredkingham** [comment]
so at the moment its if they've been on the bacteraemia list within the last 6 months. Do you want a different tag if they are currently on the bacteraemia?

**Comment by emmanuelwey** [comment]
yes as in an active tag green perhaps, and have the functionality to look for both

**Comment by fredkingham** [comment]
@emmanuelwey take a look at http://elcid-rfh-021.herokuapp.com/#/list/haem 

(I haven't used green, as i've tried to use complementary colours, however I have the artistic talent of a dead sloth so feel free to criticise!)

**Comment by davidmiller** [comment]
I think something like this for the labels might make them sit on the same baseline as the text: 

```css
    margin-top: 5px;
    display: inline-block;
    padding-top: 4px;
```
