### ISSUE TITLE
Add existing patient doesn't show existing location

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#136]
When we add an existing patient with an existing episode, their location should be loaded in, its not, the demographics get filled but the location does not

**Comment by fredkingham** [comment]
Maybe this isn't necessary, if we're opening another episode, I just find it weird that their location wouldn't be filled in with their current location. Discussion needed

**Comment by davidmiller** [comment]
@fredkingham Is this still relevant ?
What's the current behaviour ?
