### ISSUE TITLE
RFH Backups

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid-rfh#142]
- [x] Start nightly DB backups
- [x] Write a tested 'restore from backup' script
- [x] Move them to Test server
- [ ] Make size estimations
- [ ] contact our friends in IT about "where do we put it"

**Comment by fredkingham** [comment]
This is pending the inclusion of lab tests as that will significantly increase the data we are storing.

**Comment by davidmiller** [comment]
We've been storing backups off-box for years.
