### ISSUE TITLE
Update Home Page:

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid-rfh#15]
As a Doctor I need to find the details of my patient's condition so that I can give advice and answer questions.

Update home page to contain simply:

- [ ] Search 
- [ ] List select

**Comment by fredkingham** [comment]
Its not exactly the same as the designs as I've fiddled around to make it look nicer, I think we may need large icons like the previous screen http://elcid-rfh-test.openhealthcare.org.uk/#/
