### ISSUE TITLE
Group the tests by lab number and date ordered in the record panel

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#251]

**Comment by davidmiller** [comment]
21/Apr/17 POS S.aureus Gram +ve cocci chains FISH Negative
22/Apr/17 NEG

**Comment by davidmiller** [comment]
We investigated multiple different avenues e.g. upstream filtering libraries, our own, naive 'this should be easy' approaches. Turns out this is significantly more complex than initially imagined.
