### ISSUE TITLE
When you spin up a new instance of clinical advice, when I press save, clinical advice is not showing

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#271]
I create a new heroku instance
I create a patient
I create a realistic blood culture
I create a realistic clinical advice
I press save
No timeline appears, nothing appears.
The post request seems to work fine.
No error is shown.
Refresh the page and the clinical advice appears.
Only reproducible with the first patient/clinical advice added to a clean server. If you just delete all patients on an existing server everything seems to work inline with expectations.

**Comment by davidmiller** [comment]
Closing this for now - we can re-open if this resurfaces.
