### ISSUE TITLE
clinical advice when you change episode on the same patient goes on the previous episode

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#273]
go to a patient with multiple episodes, of the url /patient/{{ patient_id }}.
go to a previous episode, add some clinical advice
that advice appears in the timeline for the latest, ie the other, episode

**Comment by fredkingham** [comment]
currently fixed on RFH test

**Comment by davidmiller** [comment]
@fredkingham  Is the fix mentioned above now deployed?
