### ISSUE TITLE
card list card should point to the episode not the patient

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#278]

**Comment by davidmiller** [comment]
@fredkingham Do we do this yet ?

**Comment by fredkingham** [comment]
yep, I think we're good.

https://github.com/openhealthcare/elcid-rfh/blob/v0.3.7/elcid/templates/partials/card_without_results.html#L10

https://github.com/openhealthcare/elcid-rfh/blob/v0.3.7/elcid/templates/partials/card_with_results.html#L5
