### ISSUE TITLE
Add the additional organisms

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#285]
Emmanuel has sent through a list of organisms in a csv, add them to the look up lists

**Comment by fredkingham** [comment]
group A streptococcus = Strep pyogenes

Beta-haemolytic streptococcus Group A

Beta-haemolytic streptococcus Group B
Streptococcus agalactiae

**Comment by davidmiller** [comment]
Merged into 0.3.7 - closing
