### ISSUE TITLE
Remove models that we don't use from elcid-rfh

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#315]
We have a lot of subrecords in elcid-rfh that we don't use. Can we remove them?

Remove the below models and all related form and display templates
- [x] ContactDetails
- [ ] Carers
- [x] DuplicatePatient
- [x] PresentingComplaint
- [x] ConsultantAtDischarge
- [x] SecondaryDiagnosis
- [x] PastMedicalHistory
- [x] GeneralNote
- [x] Travel
- [ ] Iv_stop
- [x] Allergies
- [x] Todo
- [x] Hiv_no
- [x] MicrobiologyTest
- [x] Appointment

**Comment by pacharanero** [comment]
Iv_stop is referenced from `class Antimicrobial` (`reason_for_stopping = ForeignKeyOrFreeText(Iv_stop)`) hence I haven't removed it.
