### ISSUE TITLE
Review dev api lab test creation

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#318]
using branch v0.3.0.rc2

RFH will be using upstream lab tests. The plan is that when a patient is created, we query an upstream server for all of their lab tests and load them.

We need to somehow mimic this flow when we are working locally. To do this we have [the dev api](https://github.com/openhealthcare/elcid-rfh/blob/v0.3.0rc1/intrahospital_api/apis/dev_api.py#L211).

This creates us some mock lab tests using the reference range.

Please review this and create a basic algorithm realistic data for the Full blood count. Unit tests are also required.

In order to do the setup for this, 

 - [x] we need to go to the admin section for user and add all of the user profile permissions (there should be 4 add all of them). 

<img width="1055" alt="screen shot 2017-12-12 at 12 31 26" src="https://user-images.githubusercontent.com/2175455/33884659-71ada12a-df38-11e7-983b-9c43d2721c6e.png">

Criteria
- [ ] lab tests for full blood count should be created with reasonable parameters

**Comment by davidmiller** [comment]
Closing this as it's been sat for almost a year and the whole dev/prod API has been refactored at least once since!
