### ISSUE TITLE
Location model in elCID is inconsistent with model in Opal

### ISSUE THREAD

**Issue by pacharanero** [openhealthcare/elcid-rfh#320]
It would be nice to be able to use opal superclasses for much of the non-bespoke data model elements in elCID. Some work has already been done along these lines - see #313 

In the process of doing this work we found that Location is going to need updating and refactoring but it doesn't look particularly straightforward, in that it's probaly going to require some upstream changes to Opal, before that superclass is suitable as a 'drop in' replacement for the elCID-rfh implementation. And care will need to be taken that the changes don't adversely affect elCID-uch

As discussed with @davidmiller

**Comment by pacharanero** [comment]
the relevant sections of code:

https://github.com/openhealthcare/elcid-rfh/blob/70cc90abeba8d9f965cfa32ce5ff3912f50ba16b/elcid/models.py#L126

https://github.com/openhealthcare/opal/blob/9a09e77f887e5484049b5d109a81dad75d843339/opal/models.py#L1422

**Comment by davidmiller** [comment]
@fredkingham I don't think we need the LocationCategory lookuplist any more ?

Can we alter this to be a subclass of Opal Location with an added Provenance field?
Incidentally, Is provenance ever used - could we query to find out?

**Comment by davidmiller** [comment]
I suspect we're unlikely to make this a priority short-medium term.
Location will change upstream at some stage, once that's done we'll review here.
Killing the fields that are never populated though.
