### ISSUE TITLE
Convert Antimicrobial into a subclass of Treatment

### ISSUE THREAD

**Issue by pacharanero** [openhealthcare/elcid-rfh#321]
class Antimicrobial in elCID-RFH is a specialised class Treatment from Opal models, but is currently not handled as a subclass of this generic Opal model.

Reviewing the code with @davidmiller it's something that needs some thought and planning.

https://github.com/openhealthcare/elcid-rfh/blob/70cc90abeba8d9f965cfa32ce5ff3912f50ba16b/elcid/models.py#L347

https://github.com/openhealthcare/opal/blob/v0.9.1/opal/models.py#L1448

**Comment by davidmiller** [comment]
This is highly unlikely to be a priority in the near-medium term.
It would be more 'correct', but highly involved, expensive, time consuming and with minimal real world user or technical benefit.
Closing as shelved indefinitely pending a compelling reason to do it.
