### ISSUE TITLE
Full Blood Count blood test

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#323]
so as long as your permissions are set up correctly you should be able to go to 

http://127.0.0.1:8000/#/patient/{{ patient id }}/test_results

and see all of the tests.

scroll down to FULL BLOOD COUNT
There will be a series of numbers denoting trends.

this is probably not the best way to display this data.

I'm not sure about your plans and we will probably have to pair program this but...

http://127.0.0.1:8000/#/patient/{{ patient id }}/json_dump_view will show us how we're bringing this in. If you look at Full Blood Count, you can see how we cut this data, we bring in Full Blood Count as a single test, and all previous tests as different tests.

**Comment by davidmiller** [comment]
This has been deployed for months - closing this issue
