### ISSUE TITLE
Create a heroku release for the 0.3.0

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#336]
We would like a heroku release done for v0.3.0 and stories done it.

- [x] create a heroku release of the format elcid-rfh-030.herokuapp.com

- [x] make sure migrations, look up lists are created and the proper super user is created.

- [ ] run through /stories/ and make sure everything passes

- [ ] update slack with the correct release

- [ ] update the deployment doc https://docs.google.com/spreadsheets/d/18lO4fb-YEMxuIQ1tqU6x_9-_Nf9rLaFB1u_PmReEanE/edit#gid=0 with the latest heroku release

**Comment by pacharanero** [comment]
we've hit an issue with request.read() turning up empty values, when print request.data contains data. It's probably since the 0.10.0 Opal upgrade and may be related to DjangoRestFramework upgrade. This ticket is 'paused' while we work out what's going on.

**Comment by davidmiller** [comment]
0.3.0 is deployed long ago - closing this pre-release Ticket.
