### ISSUE TITLE
Create a TB plugin and patient lists.

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#338]
- [x] outside an application directory.
run the opal start plugin command for tb.
- [x] create a directory called apps in elcid-rfh with an __init__.py
- [x] copy directory inside, ie not the directory named opal-tb in to the apps directory
- [x] update the installed apps
- [x] create a [patient list](http://opal.openhealthcare.org.uk/docs/v0.9.1/guides/list_views/)
- [x] add some patients and make sure everything works as expected

**Comment by pacharanero** [comment]
unable to save patients and fully test, because of request issue @davidmiller is aware of and investigating

**Comment by pacharanero** [comment]
using workaround have now got it saving patients

**Comment by pacharanero** [comment]
Tickets #339 and #340 are all related and have been handled in the same branch https://github.com/openhealthcare/elcid-rfh/tree/338-Create-a-TB-plugin-and-patient-lists

**Comment by pacharanero** [comment]
from #340  

We use categories to tell us what sort of episode detail we display when we click through.

- [x] Create a new [episode category](http://opal.openhealthcare.org.uk/docs/v0.9.1/reference/episode_categories/), 

- [x] Change the episode_category.detail_template property to something like 
'detail/tb.html'

**Comment by pacharanero** [comment]
from #339 

We have a basic flow for adding a patient. 

RFH has access to a demographics api service, that will go off and look up patients. 

We have a pathway that goes off and does this for us in https://github.com/openhealthcare/elcid-rfh/blob/v0.3.0/elcid/pathways.py#L48

- [x] Create a pathway similar to this (with a different slug) that just uses the first step
- [x] Change the save method to save the tag 'TB' and set the episode category to TB
- [x] Change the patient list to inherit from TaggedPatientList with a property `tag` that will equal TB

#### Acceptance Critera
You should now have a patient list and a pathway that will add people to that list
