### ISSUE TITLE
controller for Add TB Patient should always create a new episode

### ISSUE THREAD

**Issue by pacharanero** [openhealthcare/elcid-rfh#344]
In the new TB Plugin fro Elcid, adding an existing patient to the TB service may, for example, result in the **existing** episode being re-tagged "TB" instead of "inpatient".

Adding a new TB patient should always create a new episode (in addition to any other existing episodes)

@fredkingham I've recorded this issue following our conversation today but please let me know if I've misunderstood the details or context.

**Comment by davidmiller** [comment]
@fredkingham are we dealing with this now or do we need to review?

**Comment by davidmiller** [comment]
The episode strategy is completely re-thought since Jan '18 - 1 per service, never closing.
