### ISSUE TITLE
raise the font size on input text/selects

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#353]
only for the RFH, change the form-control font size to 16 rather than 14.

**Comment by fredkingham** [comment]
so interestingly in opal.css there is 

.modal .btn,
.modal select,
.modal input {
  font-size: 18px;
}

there's also
.modal .form-control {
    height: 44px;
}

but this won't effect pathways causing the issue we saw earlier. 

It also won't effect inline forms, text areas or check boxes.

**Comment by davidmiller** [comment]
I think we just shelve this for now. Closing.
