### ISSUE TITLE
Symptoms for TB are important, we need to display them differently.

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#356]
remove the duration field entirely.

**Comment by fredkingham** [comment]
At the moment we have the many to many select parts.
We want symptom (singular)
then how many days ago was it.
[ days ], [ month ], [ year ]

We want to store the time delta from when the form was filled in the first time. As well as a calculated this is when this happened. (ie calculating the time delta)

**Comment by davidmiller** [comment]
This is from the initial TB development module - now superseded.
