### ISSUE TITLE
Rename Diagnosis Details field.

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid-rfh#36]
It is not clear what is intended to be included in the details field of Diagnosis / Issues.

In multiple sessions observing users who are new to the system encounter this field, they pause, and are not entirely sure what it's for or what they should be recording here.

The suggestion from @emmanuelwey is to rename it to "Further Information".

This may well be a useful change for openhealthcare/elcid as the same thing is seen there.
Thoughts from @GabPoll @michaeledwardmarks welcome with regards to making a broader change.

**Comment by GabPoll** [comment]
Seems like a good suggestion. I'm too much of an experienced user to be affected, but good to watch new users. I can see how "further info" may be less ambiguous.

**Comment by davidmiller** [comment]
Updated on the RFH Test server
