### ISSUE TITLE
RFH Lab Tests are running once an hour rather than once every 5 mins

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#408]
At the moment the batch patient load loads takes between 2 and 5 mins.

This is because we iterate through demographics for the non reconciled. The batch patient load takes significantly less.

I would suggest updating to run every 6 mins.

We can look at updating the demographics logic at a different point.

**Comment by davidmiller** [comment]
Closing as we now have separate processes for these
