### ISSUE TITLE
Categorise RFH Tests

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#411]
Can we organise the the lab tests as they come through from winpath into categories. This is to allow the us to build fast navigation that is more intuitive to our users.

At the moment some categorisation has been done in https://github.com/openhealthcare/elcid-rfh/blob/v0.3.3/elcid/api.py 

Realistically we want this moved into a constants file, a dictionary structure that will allows us to lookup from test name to the category. The constants file should sit in the elcid directory as it is hospital dependent rather than api dependent.

**Comment by pacharanero** [comment]
@fredkingham do we have a list of Every Test Ever yet?

**Comment by pacharanero** [comment]
I have reordered the extract by descending frequency of occurrence and extracted just the test names.

top 100 here:
FULL BLOOD COUNT
LIVER PROFILE
UREA AND ELECTROLYTES
RENAL PROFILE
BONE PROFILE
CHOLESTEROL/TRIGLYCERIDES
URINE SCREENING TEST
IRON STUDIES
C REACTIVE PROTEIN
CLOTTING SCREEN
THYROID FUNCTION TESTS
MRSA SCREEN
B12 AND FOLATE SCREEN
HBA1C (DCCT)
URINE PROTEIN/CR RATIO
COMMENT
RESPIRATORY PCR
HAEMATINICS
FULL BLOOD COUNT RNOH
IMMUNOGLOBULINS
SERUM LIGHT CHAINS
GLUCOSE
ESR
URINE ALB:CREAT RATIO
MAGNESIUM
25-OH VITAMIN D
LYMPHOCYTE SUBSETS
PROTEIN ELECTROPHORESIS
STOOL CULTURE
BICARBONATE
FULL BLOOD GROUP
ANTIBODY SCREEN
GAMMA-GT
HISTOLOGY
BLOOD CULTURE
CHLAMYDIA / GC SDA ASSAY
SAMPLE COMMENT
IMMUNODEFICIENCY PANEL
ANA BATTERY
SYPHILIS SEROLOGY
URATE
INR
AMYLASE
FILM REPORT
PROTHROMBIN TIME
CARDIAC TROPONIN T
GENITAL SWAB
PTH
WOUND SWAB CULTURE + SENS
NT PRO-BNP
CLOST. DIFFICILE TOXIN
HIV 1 + 2 ANTIBODIES
GENTAMICIN LEVEL
TISSUE BATTERY
TISSUE TRANSGLUTAMINASE
TACROLIMUS
RETICULOCYTE COUNT
ANC HAEMOGLOBINOPATHY SCR
HIGH VAGINAL SWAB
ENZ.CREATININE
SYPHILIS ANC REQUESTS
CMV PCR
SPUTUM CULTURE
HEPATITIS B SURFACE AG
HIV VIRAL LOAD PCR ASSAY
CARBAPENEMASE SCREEN
ANTI HBS
HCV PCR
PREVIOUS HEPATITIS SCREEN
PSA
AFP
URINE PROTEIN CONCENTR
FIBRINOGEN
PROTHROMBOTIC SCREEN 1
NOSE SWAB
HEPARIN RATIO
LACTATE DEHYDROGENASE
QUANTIFERON TB GOLD IT
HEPATITIS C ANTIBODY
COMPLEMENT
CREATINE KINASE
CARDIAC PROFILE
TOTAL PROTEIN
URINE ELECTROPHORESIS
SERUM AMYLOID A
BONE / TISSUE / BIOPSY
UNPROCESSED SAMPLE COMT
AFB : CULTURE
ARTERIAL BLOOD GASES
HELICO. PYLORI  AGN. TEST
CREATININE CLEARANCE
ASCITIC FLUID
GASTROENTERITIS PCR
ATYPICALPNEUMONIA PCR
THROMBIN TIME
PI
FSH
RHEUMATOID FACTOR
HBV DNA
ALT

**Comment by pacharanero** [comment]
The relative frequency of the occurrence of these tests is heavily skewed I think, probably by this hospital being a tertiary care and research facility.

Some tests which are very very common in 'routine' primary care and secondary care practice did not make the top 100 here.

But the groupings should be relatively applicable everywhere.

**Comment by davidmiller** [comment]
> The relative frequency of the occurrence of these tests is heavily skewed I think, probably by this hospital being a tertiary care and research facility.

Quite :)

**Comment by davidmiller** [comment]
Merged: Closing
