### ISSUE TITLE
InitialPatientLoad should never be updated by the front end

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#427]
We have had an issue where the initial patient load for a patient is stuck in a constant state of `running`

To reproduce on dev.
Add a patient through the front end.
Go to the admin change the initial patient load to `running`.
Refresh the patient in the patient detail view.
In a different tab set the initial patient load for the patient to `success`.
Then add a blood culture in the patient detail view.
The patient now has an initial patient load of running.

Stop this.

**Comment by davidmiller** [comment]
@fredkingham did we deploy a fix to this already ?

**Comment by fredkingham** [comment]
This has already been deployed.
