### ISSUE TITLE
Unable to edit treatment !

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid-rfh#446]
```bd5450d9be64.js:2691 Error: [ng:areq] Argument 'TreatmentFormCtrl' is not a function, got undefined```

**Comment by davidmiller** [comment]
@fredkingham I can't imagine we haven't fixed this - we'd have heard about it - can we check and close if so...

**Comment by fredkingham** [comment]
The `treatment_record.js` still declares `TreatmentFormCtrl` but this does not exist. Do we need it. I not we should delete it. If so, what did it do.

Either way the current state is incorrect.

**Comment by davidmiller** [comment]
Treatment has changed substantially since 2018 and been tested.
