### ISSUE TITLE
pytz.exceptions.AmbiguousTimeError raised by lab tests.

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#454]
In someways this is actually an opal bug https://github.com/openhealthcare/opal/issues/1577

Create a `set_datetime_ordered` to use that method until a solution is merged into opal.

(Its actually slightly different as we don't know for certain was tz is being used by the upstream system).

**Comment by davidmiller** [comment]
It's an opal bug, closing
