### ISSUE TITLE
HIV, Hep B Hep C data

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#469]
If the patient has ever had an HIV, Hep B, Hep C test. Please can we bring and display this data?

- [ ] Add a query that checks for lab tests for all time for HIV, Hep B, Hep C.
- [ ] Add this to the initial load patient.
- [ ] Display this on the front page for TB Patients.
- [ ] Ask Emmanuel if he wants this displayed anywhere for him

**Comment by davidmiller** [comment]
Done.
