### ISSUE TITLE
batch load count is not being updated

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#479]
please can we make sure that the `count` for a batch patient load, if we are going to use it, is updated correctly

**Comment by fredkingham** [comment]
This has been pushed until after the initial TB release

**Comment by davidmiller** [comment]
@fredkingham is this part of #528 now?

**Comment by fredkingham** [comment]
yep, this should be fixed. We've got examples of this coming through, but will assign to the mile stone so we can check again when upstream issues are resolved.
