### ISSUE TITLE
TB Phase 0

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid-rfh#487]
- [x] Hide lists menu button
- [x] Failed search to go to the right add patient screen / steps 
- [x] Pathway title to not say TB
- [x] Hide appointments panel
- [x] Borders on print advice: Make them greyscale by default
- [x] Add an icon to imaging

**Comment by fredkingham** [comment]
- [ ] Add a lookup list  of `state` which is a proxy for stage at this time, populated from a lookup list

**Comment by davidmiller** [comment]
This is done and deployed, closing.
