### ISSUE TITLE
Create a prototype of the new blood culture form

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid-rfh#539]
The new blood culture form will be a per lab test (ie per lab number).

Each lab test will have one or more isolates.

We will just use a FK or FT options for Gram Stain/Fish Stain/Sepsityper and keep Result how it is at the moment.

**Comment by fredkingham** [comment]
wip prototype for display to Emmanuel on 539-new-blood-culture-prototype-form. I'll show him tomorrow.

<img width="974" alt="screen shot 2018-10-18 at 15 35 38" src="https://user-images.githubusercontent.com/2175455/47162453-e40ced00-d2eb-11e8-81fe-767aa47ca127.png">

**Comment by davidmiller** [comment]
Closing this as we've now reviewed the prototype.
