### ISSUE TITLE
Secret key found in repo

### ISSUE THREAD

**Issue by josh-ho** [openhealthcare/elcid-rfh#798]
Hello 👋 

I noticed that you have a secret key stored in your repo: https://github.com/openhealthcare/elcid-rfh/blob/master/elcid/settings.py#L106

You may want to remove the key, and the git history (https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository)

Might I also suggest to rotate the key in case someone else may have copied the key and used it for other purposes.

**Comment by davidmiller** [comment]
Hi @josh-ho Thanks for letting us know!

We've updated the deployment scripts now to not use the one in settings.py in production.
