### ISSUE TITLE
ICU Consult Proforma

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid-rfh#855]
For Clinical Advice, when reason for interaction is ICU round, some additional fields to enter and display:

Ventilation
 - Ventilated [Y | N]
 - Type: [NIV | Intubated]
 - Fio2: [char]
 - Comments [Text]

Inotropic Support
 - Inotropic [Y | N]
 - Drug [Char lookuplist]
 - Dose [Char]

Others
- Meld Score 
- Sofa Score
- Temperature 

Model suggestion:

```python

Class ICUStatus:
  date = DateField()
  ventilation_type = ChoicesField()
  fi02 = CharField()
  ventilation_comments = TextField()
  inotropic_drug = LookuplistField()
  inotropic_dose = CharField()
  meld_score = CharField()
  sofa_score = CharField()
```

Inotropic drugs: 
noradrenaline
adrenaline
dobutamine
vasopressin
inoximone
milrinone
levosemendin
metaraminol

**Comment by blu3id** [comment]
To be a pedant:
There is a significant difference between inotropes and vasopressors. Some drugs do both (adrenaline) others have a predominant focus.

To save complexity of trying to correctly classify each would suggest some form of naming for such drugs as "cardiovascular support"

**Comment by davidmiller** [comment]
Thanks for being a pedant @blu3id  :) 

In the end we wound up separating Vasopressor and Inotropes - this is now reviewed and pending a deployment this evening.
